django-models/bbs/urls.py
from django.conf.urls import url

from . import views

app_name = 'bbs'
urlpatterns = [
    url(r'^$', views.article_list, name = 'list'),
    url(r'^(?P<pk>\d+)/$', views.article_detail, name = 'article_detail'),
    url(r'^add/$', views.article_add, name = 'article_add'),
    url(r'^markdown/$', views.article_markdown, name = 'markdown'),
    url(r'^(?P<pk>\d+)/modify/$', views.article_modify, name = "article_modify"),
    url(r'^(?P<pk>\d+)/delete/$', views.article_delete, name = 'article_delete'),

]

django-models/models/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bbs import urls as bbs_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^bbs/', include(bbs_urls)),
]

django-models/bbs/models.py
from django.db import models
from django.utils import timezone


class Title(models.Model):
    title = models.CharField(max_length = 50)
    created_date = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey('auth.User')

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.ForeignKey(Title, on_delete = models.CASCADE, blank = False, null = False)
    subtitle = models.CharField(max_length = 100)
    created_date = models.DateTimeField(default = timezone.now)
    description1 = models.TextField(blank = True, null = True)
    examples = models.TextField(blank = True, null = True)
    description2 = models.TextField(blank = True, null = True)

    def __str__(self):
        return self.subtitle

django-models/models/settings.py
"""
Django settings for models project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!#-borcjj8%hg%&9*w%^11@gu9$mz4-ity^ge(bv4b=rygkz9j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bbs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'models.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'models.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    STATIC_DIR,
)

django-models/models/wsgi.py
"""
WSGI config for models project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "models.settings")

application = get_wsgi_application()

django-models/bbs/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import render, get_list_or_404, redirect

from .models import Article, Title

User = get_user_model()


def article_list(request):
    latest_article_list = get_list_or_404(
        Article.objects.order_by('created_date')
    )
    context = {
        'latest_article_list': latest_article_list,
        'title': Title.objects.first(),
    }
    return render(request, 'bbs/article_list.html', context = context)


def article_detail(request, pk):
    article = Article.objects.get(pk = pk)
    context = {
        'article': article,
        'pk': pk
    }
    return render(request, 'bbs/article_detail.html', context)


def article_add(request):
    if request.method == 'GET':
        user = get_user_model()
        context = {
            'article': Article(),
        }
        return render(request, 'bbs/article_add.html', context)

    elif request.method == 'POST':
        data = request.POST
        # user = User()
        print(data)
        # print('user id:', user)
        article = Article.objects.create(
            # author = 1,
            title_id = 1,
            subtitle = data['subtitle'],
            description1 = data['description1'],
            examples = data['examples'],
            description2 = data['description2'],
        )
        article.save()
        return redirect('bbs:article_detail', pk = article.pk)


def article_markdown(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'bbs/article_markdown.html', context)


def article_modify(request, pk):
    article = Article.objects.get(pk = pk)
    if request.method == 'GET':
        context = {
            'article': article,
            'pk':pk
        }
        return render(request, 'bbs/article_modify.html', context)
    elif request.method == 'POST':
        data = request.POST
        article.subtitle = data['subtitle']
        article.description1 = data['description1']
        article.examples = data['examples']
        article.description2 = data['description2']
        article.save()
        return redirect('bbs:article_detail', pk = article.pk)


def article_delete(request, pk):
    if request.method == 'POST':
        article = Article.objects.get(pk = pk)
        article.delete()
        return redirect('bbs:list')
    else:
        return HttpResponse('Method "GET" is not allowed.')

django-models/templates/bbs/article_add.html
{% extends 'bbs/base.html' %}
{% block content %}

<body>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="subtitle">제목</label>
                <input class="form-control" type="text" name="subtitle" id="subtitle" placeholder="제목">
            </div>

            <div class="form-group">
                <label for="description1">설명</label>
                <textarea class="form-control" name="description1" id="description1" cols="30" rows="10"></textarea>
            </div>

            <div class="form-group">
                <label for="examples">Sample Code</label>
                <textarea class="form-control" name="examples" id="examples" cols="30" rows="10"></textarea>
            </div>

            <div class="form-group">
                <label for="description2">Sample Code 설명</label>
                <textarea class="form-control" name="description2" id="description2" cols="30" rows="10"></textarea>
            </div>

            <button type="submit" class="btn btn-primary center-block">Submit</button>
        </form>
    </div>
</body>


{% endblock %}

django-models/templates/bbs/article_detail.html
{% extends 'bbs/base.html' %}
{% block content %}
<body>
    <div class="container">
        <form action="{% url 'bbs:article_delete' pk=article.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger pull-right">DELETE</button>
        </form>

        <a href="{% url 'bbs:list' %}" class="btn btn-primary pull-right">Back to List</a>
        <a href="{% url 'bbs:article_modify' pk=article.pk %}" class="btn btn-primary pull-right">Modify</a>
            <h3>{{ article.subtitle }}</h3>
        {% if article.description1 %}
            <p>{{ article.description1|linebreaksbr }}</p>
        {% else %}{% endif %}
        {% if article.examples %}
            <pre>{{ article.examples|linebreaksbr }}</pre>
        {% else %}{% endif %}
        {% if article.description2 %}
            <p>{{ article.description2|linebreaksbr }}</p>
        {% else %}{% endif %}
    </div>
</body>
{% endblock %}

django-models/templates/bbs/article_list.html
{% extends 'bbs/base.html' %}
{% block content %}
<body>
<div class="container">
    <a href="{% url 'bbs:article_add' %}" class="btn btn-primary pull-right">add</a>
    <a href="{% url 'bbs:markdown' %}" class="btn btn-primary pull-right">markdown</a>

    <h2>{{ title }}</h2>
    {% for article in latest_article_list %}
        <h3><a href="{% url 'bbs:article_detail' pk=article.pk %}">{{ article.subtitle }}</a></h3>
        <p class="lead">{{ article.description1|truncatechars:70 }}</p>
    {% endfor %}
</div>

</body>
{% endblock %}

django-models/templates/bbs/article_markdown.html
{% extends 'bbs/base.html' %}
{% block content %}
<body>
<div class="container">
<div><a href="{% url 'bbs:list' %}" class="btn btn-primary pull-right">Back to List</a></div>
<br><br>
<pre>
    {% for article in articles %}

        <p>### {{ article.subtitle }}</p>
        {% if article.description1 %}
        <p>{{ article.description1|linebreaksbr }}  </p>
        {% else %}{% endif %}
        {% if article.examples %}
<span>```python</span>
<p>{{ article.examples|linebreaksbr }}</p><span>```</span>
        {% else %}{% endif %}
        {% if article.description2 %}
        <p>{{ article.description2|linebreaksbr }}  </p>
        {% else %}{% endif %}
    {% endfor %}
</pre>
</div>
</body>
{% endblock %}

django-models/templates/bbs/article_modify.html
{% extends 'bbs/base.html' %}
{% block content %}

<body>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="subtitle">제목</label>
                <input class="form-control" type="text" name="subtitle" id="subtitle" placeholder="제목" value="{{ article.subtitle }}">
            </div>

            <div class="form-group">
                <label for="description1">설명</label>
                <textarea class="form-control" name="description1" id="description1" cols="30" rows="10">{{ article.description1 }}</textarea>
            </div>

            <div class="form-group">
                <label for="examples">Sample Code</label>
                <textarea class="form-control" name="examples" id="examples" cols="30" rows="10">{{ article.examples }}</textarea>
            </div>

            <div class="form-group">
                <label for="description2">Sample Code 설명</label>
                <textarea class="form-control" name="description2" id="description2" cols="30" rows="10">{{ article.description2 }}</textarea>
            </div>

            <button type="submit" class="btn btn-primary center-block">Submit</button>
        </form>
    </div>
</body>


{% endblock %}

django-models/templates/bbs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Django</title>
</head>

<header>
    <div class="page-header">
        <h1 class=""><a href="{% url 'bbs:list' %}">Django Introduction to Models</a></h1>
    </div>
</header>

{% block content %}
{% endblock %}
</html>